; Lowercase letters
Hotkey "$~a", (*) => HandleKeypress("a")
Hotkey "$~b", (*) => HandleKeypress("b")
Hotkey "$~c", (*) => HandleKeypress("c")
Hotkey "$~d", (*) => HandleKeypress("d")
Hotkey "$~e", (*) => HandleKeypress("e")
Hotkey "$~f", (*) => HandleKeypress("f")
Hotkey "$~g", (*) => HandleKeypress("g")
Hotkey "$~h", (*) => HandleKeypress("h")
Hotkey "$~i", (*) => HandleKeypress("i")
Hotkey "$~j", (*) => HandleKeypress("j")
Hotkey "$~k", (*) => HandleKeypress("k")
Hotkey "$~l", (*) => HandleKeypress("l")
Hotkey "$~m", (*) => HandleKeypress("m")
Hotkey "$~n", (*) => HandleKeypress("n")
Hotkey "$~o", (*) => HandleKeypress("o")
Hotkey "$~p", (*) => HandleKeypress("p")
Hotkey "$~q", (*) => HandleKeypress("q")
Hotkey "$~r", (*) => HandleKeypress("r")
Hotkey "$~s", (*) => HandleKeypress("s")
Hotkey "$~t", (*) => HandleKeypress("t")
Hotkey "$~u", (*) => HandleKeypress("u")
Hotkey "$~v", (*) => HandleKeypress("v")
Hotkey "$~w", (*) => HandleKeypress("w")
Hotkey "$~x", (*) => HandleKeypress("x")
Hotkey "$~y", (*) => HandleKeypress("y")
Hotkey "$~z", (*) => HandleKeypress("z")

; Numbers
Hotkey "$~1", (*) => HandleKeypress("1")
Hotkey "$~2", (*) => HandleKeypress("2")
Hotkey "$~3", (*) => HandleKeypress("3")
Hotkey "$~4", (*) => HandleKeypress("4")
Hotkey "$~5", (*) => HandleKeypress("5")
Hotkey "$~6", (*) => HandleKeypress("6")
Hotkey "$~7", (*) => HandleKeypress("7")
Hotkey "$~8", (*) => HandleKeypress("8")
Hotkey "$~9", (*) => HandleKeypress("9")
Hotkey "$~0", (*) => HandleKeypress("0")

; Special keys
Hotkey "$~Space", (*) => HandleKeypress("Space")
Hotkey "$~Enter", (*) => HandleKeypress("Enter")
Hotkey "$~Backspace", (*) => HandleKeypress("Backspace")

; Uppercase letters
Hotkey "$~+a", (*) => HandleKeypress("A")
Hotkey "$~+b", (*) => HandleKeypress("B")
Hotkey "$~+c", (*) => HandleKeypress("C")
Hotkey "$~+d", (*) => HandleKeypress("D")
Hotkey "$~+e", (*) => HandleKeypress("E")
Hotkey "$~+f", (*) => HandleKeypress("F")
Hotkey "$~+g", (*) => HandleKeypress("G")
Hotkey "$~+h", (*) => HandleKeypress("H")
Hotkey "$~+i", (*) => HandleKeypress("I")
Hotkey "$~+j", (*) => HandleKeypress("J")
Hotkey "$~+k", (*) => HandleKeypress("K")
Hotkey "$~+l", (*) => HandleKeypress("L")
Hotkey "$~+m", (*) => HandleKeypress("M")
Hotkey "$~+n", (*) => HandleKeypress("N")
Hotkey "$~+o", (*) => HandleKeypress("O")
Hotkey "$~+p", (*) => HandleKeypress("P")
Hotkey "$~+q", (*) => HandleKeypress("Q")
Hotkey "$~+r", (*) => HandleKeypress("R")
Hotkey "$~+s", (*) => HandleKeypress("S")
Hotkey "$~+t", (*) => HandleKeypress("T")
Hotkey "$~+u", (*) => HandleKeypress("U")
Hotkey "$~+v", (*) => HandleKeypress("V")
Hotkey "$~+w", (*) => HandleKeypress("W")
Hotkey "$~+x", (*) => HandleKeypress("X")
Hotkey "$~+y", (*) => HandleKeypress("Y")
Hotkey "$~+z", (*) => HandleKeypress("Z")

; Punctuation
Hotkey "$~,", (*) => HandleKeypress(",")
Hotkey "$~.", (*) => HandleKeypress(".")
Hotkey "$~;", (*) => HandleKeypress(";")
Hotkey "$~'", (*) => HandleKeypress("'")
Hotkey "$~-", (*) => HandleKeypress("-")
Hotkey "$~=", (*) => HandleKeypress("=")
Hotkey "$~/", (*) => HandleKeypress("/")
Hotkey "$~\", (*) => HandleKeypress("\")
Hotkey "$~[", (*) => HandleKeypress("[")
Hotkey "$~]", (*) => HandleKeypress("]")
Hotkey "$~(", (*) => HandleKeypress("(")
Hotkey "$~)", (*) => HandleKeypress(")")
Hotkey "$~{", (*) => HandleKeypress("{")
Hotkey "$~}", (*) => HandleKeypress("}")
Hotkey "$~:", (*) => HandleKeypress(":")
Hotkey "$~!", (*) => HandleKeypress("!")
Hotkey "$~?", (*) => HandleKeypress("?")
Hotkey "$~@", (*) => HandleKeypress("@")
Hotkey "$~#", (*) => HandleKeypress("#")
Hotkey "$~$", (*) => HandleKeypress("$")
Hotkey "$~%", (*) => HandleKeypress("%")
Hotkey "$~^", (*) => HandleKeypress("^")
Hotkey "$~&", (*) => HandleKeypress("&")
Hotkey "$~*", (*) => HandleKeypress("*")
Hotkey "$~_", (*) => HandleKeypress("_")
Hotkey "$~+", (*) => HandleKeypress("+")
Hotkey "$~|", (*) => HandleKeypress("|")
Hotkey "$~<", (*) => HandleKeypress("<")
Hotkey "$~>", (*) => HandleKeypress(">")
Hotkey "$~``", (*) => HandleKeypress("``")  ; Backtick needs double escape
Hotkey '$~"', (*) => HandleKeypress('"')    ; Use single quotes around the double quote
; Mouse click to hide GUI and reset word
Hotkey "$~LButton", (*) => ResetAndHideGui()
